ucsdlib/hifive

app/models/employee.rb, app/services/ldap/queries.rb, app/views/recognitions/index.html.erb, app/views/recognitions/show.html.erb, spec/models/employee_spec.rb
Fixes #40 
This PR adds very basic initial support for caching employee photos for display when they're recognized. It doesn't handle:
- Making it actually look nice
- Having a fallback icon/image when none is present
- Checking if an image already exists and determining whether to write over it or not. Because of how small these are, I'm currently assuming we always want the latest and greatest, but perhaps we could be smarter about this. thoughts?
References #40 
Hopefully this is small enough to look through at the Employee model updates and related tests.
=> employees: cache and display photos when available

Gemfile, Gemfile.lock
This gem shouldn't be necessary anymore since chromedriver is installed an run within the context of the container via docker and docker-compose.
=> bundle: remove chromedriver-helper

app/views/recognitions/_form.html.erb
Fixes #71 
Adds a label and hint clarifying to the user what an anonymous submission means. This was ported from the original Mach Form and only tweaked slightly for context (this is not a blog) and gender pronouns.
References #71 
@VivianChu - please review
=> form: clarify anonymous submission for users

Dockerfile
Fixes #62 
Updates the version of NodeJS installed into the Dockerfile to the latest 10.x version (10.13.0)
References #62 
Version 10 is an LTS branch for NodeJS, so we're safe updating to this for the foreseeable future.
Rebuild your docker image and run the tests, the app, etc. and make sure things work. All seemed fine to me other than an install warning about a GPG key signature reported in https://github.com/nodejs/node/issues/23992 which should fix itself up once the person gets their subkey updated and pushed through gpg mirrors. I'll keep an eye on it.
=> docker: update nodejs to latest 10.x version

.gitignore, Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/statistics.js, app/assets/stylesheets/application.scss, app/controllers/statistics_controller.rb, app/helpers/auth_helper.rb, app/helpers/statistics_helper.rb, app/models/recognition.rb, app/models/user.rb, app/views/statistics/index.html.erb, config/routes.rb, spec/controllers/statistics_controller_spec.rb, spec/helpers/statistics_helper_spec.rb, spec/models/recognition_spec.rb, spec/models/user_spec.rb, spec/support/user.rb
Fixes #41 
Add initial statistics support based on #41 . It's restricted to administrators, and returns a CSV when there are results available via `send_data`.
The UI is pretty hideous, but I'm assuming we'll dial that in with the help of David. I was aiming for initial feature complete.
References #41 
I intentionally tried to make these commits granular because a lot of files had to be touched. So I might work from those back to front AND/OR start with the tests.
You'll need to load some data and create a few recognitions if you want to test via the UI.
=> Add initial statistics support

app/controllers/opt_out_links_controller.rb, app/helpers/statistics_helper.rb, app/models/opt_out_link.rb, app/models/recognition.rb, config/routes.rb, config/schedule.rb, db/migrate/20181109213520_create_opt_out_links.rb, db/migrate/20181109225636_add_suppressed_to_recognitions.rb, db/schema.rb, spec/controllers/opt_out_links_controller_spec.rb, spec/controllers/statistics_controller_spec.rb, spec/factories/opt_out_links.rb, spec/models/opt_out_link_spec.rb, spec/models/recognition_spec.rb, spec/rails_helper.rb
Fixes #75 
Introduces opt out/suppression links for recognitions. It adds a `suppressed` field to Recognitions, which defaults to `false`, which is set to `true` if an opt out link is used. This data is now added to the csv export for statistics.
The opt out links expire after 6 months, and a whenever cron has been setup to check for expired links nightly and remove them. There are tests in place for this, note the use of the relatively new `travel_to` method provided by `ActiveSupport::Testing::TimeHelpers`
References #75 #22 
I tried to make individual commits to target each piece of the work. The tests would be good as well, and please let me know if i missed any!
You can create a Recognition in the UI, using this branch. Then go in to rails console and grab the `key` for the related …
=> OptOutLinks feature

app/controllers/recognitions_controller.rb, app/views/recognitions/feed.rss.builder, config/routes.rb, spec/controllers/recognitions_controller_spec.rb
Fixes #39 
Adds a basic RSS feed for recognitions. Note that while images are technically possible to include in an RSS feed, David T confirmed that the Confluence RSS feed widget cannot use them. So they're not here, alas.
References #39 
=> recognitions: add rss feed

app/controllers/recognitions_controller.rb
Fixes #89 
Switches the recognition `index` action to sort reverse chronologically. the `feed` action was already doing this, so the two were lined up as far as the way the query is constructed.
References #89 
=> recognitions: reverse chronological sort for index

app/helpers/statistics_helper.rb, spec/controllers/statistics_controller_spec.rb
Fixes #93 
Adds the description field to the generated CSV for statistics.
References #93 
=> statistics: add description to csv

app/views/recognitions/_form.html.erb, spec/system/recognition_spec.rb
Fixes #102 
Sorts employees in the select list by display name.
The default sort is by pk, which means a completely random list that would be confusing for users.
=> recognition form: sort employees in select list

app/models/employee.rb, app/services/ldap/queries.rb, spec/models/employee_spec.rb, spec/services/ldap/queries_spec.rb
whenChanged can be used to determine whether we need to update a given
local Employee record with data from that employee's LDAP record. This
should save some cycles for the nightly update script and give us more
accurate change tracking over time.
Fixes #110 
Adds a check when updating local Employee records from LDAP to ensure we only do DB writes when necessary.
References #110 
Tests and implementation of `needs_update?`
@VivianChu - please review
=> ldap: add whenChanged attribute to employees query

app/models/employee.rb, app/services/ldap/queries.rb, app/views/recognitions/index.html.erb, app/views/recognitions/show.html.erb, spec/models/employee_spec.rb
it turns out AD isn't a reliable, single source of record for employee
photos. since we don't have one, we're pulling the feature, for now
Fixes #114 
Remove the AD photo feature.
References #114 
=> photos: remove from application

app/mailers/recognition_mailer.rb, app/models/employee.rb, spec/factories/employees.rb, spec/mailers/recognition_mailer_spec.rb, spec/models/employee_spec.rb, spec/services/ldap/queries_spec.rb
Fixes #124 
Instead of persisting the entire DN value from the ldap `manager` field, we only persist the CN. @VivianChu was already parsing this out to send emails, and we should just store it in the DB this way to keep things simple.
References #124 
=> employee: only persist manager CN from dn

app/views/recognitions/front.html.erb
Fixes #137
Adds a temporary link on the landing page to recognitions for the testing group. It is assumed this will be removed later once we have a proper UI setup.
References #137
@VivianChu - please review
=> recognitions: add temp link on landing page

Dockerfile
This fixes errors for Docker for Mac folks, which is the majority of our
team.
Hopefully allows folks using Docker for Mac to build the Dockerfile image.
@VivianChu @dt-ucsd   - please review
=> docker: use no-tty for gpg commands

Capfile, config/schedule.rb, lib/tasks/nightly.rake
Fixes #149 
Adds the whenever capistrano task to ensure the cron tab gets setup on deploy.
I tested locally with a capistrano dry run and got the following:
```
00:00 git:wrapper
01 mkdir -p /tmp
02 #<StringIO:0x0000561b2136bc48> /tmp/git-ssh-hifive-production-.sh
03 chmod 700 /tmp/git-ssh-hifive-production-.sh
00:00 git:check
01 git ls-remote git@github.com:ucsdlib/hifive.git HEAD
00:00 deploy:check:directories
01 mkdir -p /pub/hifive/shared /pub/hifive/releases
00:00 git:clone
The repository mirror is at /pub/hifive/repo
00:00 git:update
01 git remote set-url origin git@github.com:ucsdlib/hifive.git
02 git remote update --prune
00:00 git:create_release
01 mkdir -p /pub/hifive/releases/20190109222616
02 git archive master | /usr/bin/env tar -x -f - -C /pub/hifive/releases/20190109222616 …
```
=> capistrano: use whenever deploy tasks

app/mailers/recognition_mailer.rb, spec/mailers/recognition_mailer_spec.rb
Fixes #155 
Adds the recognizer to the list of people in the `To:` field for the recognition email.
References #155 
=> email: add recognizer to the To: receiver list

config/schedule.rb
There was a syntax error in defining the cron entries using whenever. Those commas add up..
Also putting in an option we might want to use for production, we'll sort that out w/ Ron separately.
=> whenever: fix incorrect syntax causing midnight entries

app/models/employee.rb, spec/models/employee_spec.rb
While we were successfully deactivating employees with the nightly cron
tasks, we were forgetting to ignore those deactivated employees in the
filter query
=> employee: don't deactivate deactivated employees

Capfile, app/views/recognition_mailer/email.html.erb, config/deploy/production.rb, config/deploy/staging.rb, config/environments/production.rb
Fixes: #170 
...and some of #169 
- Removes hard-coded /h5 URL and replaces w/ `root_url`
- Sets `lib-highfive.ucsd.edu` as host for action mailer (email)
- Adds capistrano production server to config file
- Remove the sitemap role from staging config (presumably copy/paste from somewhere)
- Remove some extraneous comments in Capfile
References #169 #170 
=> Capistrano prod prep

config/deploy.rb
- Switches capistrano repo URL to https, apparently there may be ssh keys missing somewhere, and since this is a public repo doesn't seem like it matters.
- Remove `RAILS_RELATIVE_URL_ROOT` when compiling assets. We're not hosting the app off a subdirectory
References #169 
@VivianChu @jhriv  - please review
=> Capistrano relative fix

config/deploy.rb
Always deploy to `/pub/highfive` for staging and prod
References #169 
@VivianChu @rstanonik  - please review
=> capistrano: deploy to the /pub/highfive directory

Gemfile, Gemfile.lock
This provides a better rails console that we can use for local debugging
and testing. It provides much richer information than the standard
IRB/Rails console.
For example:
```
[8] pry(main)> Recognition.new.method(:generate_link).source.display
def generate_link
logger.tagged('recognition') { logger.info "sending email for recognition #{id}" }
generate_key(id)
RecognitionMailer.email(Recognition.find(id)).deliver_now
end
=> nil
```
See:
- https://github.com/pry/pry#introduction
- https://github.com/rweng/pry-rails#usage
=> gems: add pry-rails and pry-doc

Dockerfile.development, bin/docker-helper.sh, docker/test/docker-compose.yml, spec/support/capybara_selenium.rb
- Change Dockerfile.development to use Alpine
- Change Dockerfile.development to NOT install chrome/chromedriver
- Use selenium docker image for docker-compose testing
- Fix capybara/selenium configuration to support docker environment
Previously, in order to do local testing in a docker-compose environment, we had to install Chrome and chromedriver in the Dockerfile/image. Which made the image huge. This PR removes that need by leveraging a selenium image for JS testing instead.
Please clean out your existing images, and try running the docker test command from the helper script:
` bin/docker-helper.sh -t`
Hopefully this results in passing test suite, if not, please let me know!
`SELENIUM_URL: http://browser:4444/wd/hub/` for testing environment only
=> docker: support selenium testing

.circleci/config.yml, Dockerfile, Dockerfile.development, Gemfile.lock, docker/development/docker-compose.yml, docker/production/docker-compose.yml, docker/test/docker-compose.yml
Since we're using the latest version of Ruby we should be able to use the bundled version of Bundler as well.
Related, I took the opportunity to include a lesson learned from some docker-compose work on Starlight. This adds a volume cache for gems that makes the development workflow w/ gems more like using your local machine.
=> Use latest version of Bundler

.rubocop.yml, Gemfile, Gemfile.lock
It's being extracted out of rubocop to a dedicated gem
Getting ahead of the deprecation warnings.
=> rubocop: add rubocop-performance gem

Gemfile, Gemfile.lock, config/initializers/okcomputer.rb
We will need this for deploying the application to kubernetes. For now,
we are mounting under '/health' to make it easy to setup the k8s
deployment configuration
Fixes #316 
- Adds `okcomputer` gem for adding a health check endpoint
- mounts the endpoint at `/health` (see: screenshots)
Setup for a Kubernetes deployment in the future
=> Add okcomputer gem for health checks

.env.docker, README.md, docker-compose.yml, docker/docker-entrypoint.sh
Fixes #326 
This will be required for the Helm/K8s deployment so that we can ensure
that deployments after the initial deploy always use `db:migrate`
instead of the `db:create db:schema:load`.
Add some initial documentation around this to the `README`
References #326 #301 
`DATABASE_COMMAND` - Note this is not relevant for our existing deployments, since Capistrano is used to manage database rake tasks. So we don't need a PR to `env-variables` to add support for this.
=> Add DATABASE_COMMAND env var to entrypoint script

Dockerfile, docker-compose.yml
Fixes: #361
Sometime between the 2.0.2 (locked) version of Bundler and the current
version (2.1.4) the method used in the Dockerfile for customized bundler
path setup ceased to function, causing errors when starting the Rails
application. This can probably be optimized again in the future, but for
now, make it work again.
- Remove custom, optimized setup for Bundler in `Dockerfile`
- Remove custom volume for bundler in docker-compose (this seems to get out of sync frequently and require deletion/rebuilds)
This is currently blocking work on #360 and #359 
=> docker: fix bundler setup

app/models/recognition.rb, spec/models/recognition_spec.rb
Fixes #359 
The previous code took the start and end dates from the form, which came in the format of
YYYY-MM-DD, and then applies them to the `where` range query. This works
as expected for the start_date, but is problematic for the end_date
since a String date of the form YYYY-MM-DD will be turned into a
DateTime object which translates to the "beginning of that day".
This is confusing to administrators who expect Recognitions created on
the same date as their chosen end_date to be included in the results of
the statistics query. This change utilizes the Rails ActiveSupport
`end_of_day` method that gets mixed in to the `DateTime`.
References #issuenumber
See the new test demonstrating a record created on the same day as the end date in the range query being included in the results. …
=> stats: make end_date inclusive for query

.rubocop.yml, app/models/employee.rb, spec/models/employee_spec.rb
Fixes #360 
Check for missing mail attribute and do not process that record.
References #360 
run 'make up'
=> Update the populate_from_ldap function to ignore employee with no mail attr

app/models/recognition.rb, app/services/slack_notifier.rb, config/application.rb, config/environment.rb, config/environments/test.rb, spec/models/recognition_spec.rb, spec/services/slack_notifier_spec.rb, spec/spec_helper.rb
Fixes #365 
This commit adds the following:
- A new service called `SlackNotifier` that is responsible for sending a
formatted notification to a Slack channel via an incoming web hook.
This web hook url is expected to be provided via the `SLACK_WEBHOOK_URL`
env var
- An ActiveRecord callback named `notify_slack` in the `Recognition` model
class that calls the `SlackNotifier` service
- Adds `default_url_options` to the Application in `config/environment.rb`, which inherit from the
`action_mailer` settings so they are only set once. This is used in the
callback since the model does not have access to the host or dynamic
routing helpers by default. But, we need the Recognition url for the Slack message
References #365 
The High Five product owner would like more staff visibility for …
=> Add slack notification to Recognition

Gemfile, Gemfile.lock, app/mailers/recognition_mailer.rb, app/models/employee.rb, db/migrate/20200226225209_allow_employees_without_managers.rb, db/schema.rb, spec/factories/employees.rb, spec/mailers/recognition_mailer_spec.rb, spec/models/employee_spec.rb
References #369 
- Adds missing `pry-byebug` gem for debugging
- Allow `Employee` records to optionally have a `manager` instead of requiring it.
We have three scenarios that have been identified that could cause an
`Employee`, that is valid as far as the application is concerned, to not
have a `manager` attribute in LDAP
1. The `ldap_sync` script simply has not run and updated the employee record. This could happen for new employees or employees who change jobs in the library
2. The employee has a dual-assignment, and their AD record is not owned and managed by the Library
3. The employee has a dual-assignment, and their AD record is owned and managed by the Library, but their manager does not work for the Library
References #369 
The application needs to be made a bit more flexible to …
=> Optional manager

.circleci/config.yml, Dockerfile, config/application.rb, hifive/questions.yaml, hifive/templates/deployment.yaml, hifive/values.yaml
Fixes #373 
Application: Rename in the config/application.rb file to match what will
now be in the env variables for the application
Helm Chart:
Previously, we were incorrectly assuming this was the email container
host. It is the application host, which the env var name now correctly
implies
References #373 
Related env vars PR: https://github.com/ucsdlib/ops-ansible-playbooks/pull/91
Renames `APPS_H5_EMAIL_HOST` to `APPS_H5_APP_HOST`
=> Rename APPS_H5_EMAIL_HOST to APPS_H5_APP_HOST

app/models/employee.rb, app/services/ldap/filters.rb, app/services/ldap/queries.rb, spec/models/employee_spec.rb, spec/services/ldap/filters_spec.rb, spec/services/ldap/queries_spec.rb
Fixes #369 
Update ldap query to use different security group and use samaccountname instead of CN for uid.
References #369 
It's deployed to staging.
---
=> Update ldap query to use different security group

app/controllers/recognitions_controller.rb, app/controllers/sessions_controller.rb, app/helpers/recognitions_helper.rb, app/services/ldap/filters.rb, app/services/slack_notifier.rb, spec/services/slack_notifier_spec.rb
- Removes John and the related exceptions code from the `pretty_name` method
- Include and leverage the `pretty_name` method from the
`RecognitionsHelper` module in the `SlackNotifier` class
- Update the `pretty_name` method to create an interpolated string, and
also ensure that any leading and trailing whitespace are omitted via
`strip`
- Add test to demonstrate the new name display working for the `SlackNotifier`
- Makes a few additional rubocop-related updates due to namespace moves (:man_shrugging: )
=> Slack name display update
